# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('item_available_qty', models.IntegerField(default=0)),
            ],
        ),
    ]
