# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date'),
            preserve_default=False,
        ),
    ]
